create table orders (
	id INT,
	product VARCHAR(50),
	quantity INT
);
insert into orders (id, product, quantity) values (1, 'Horseradish - Prepared', 3);
insert into orders (id, product, quantity) values (2, 'Wine - Cousino Macul Antiguas', 5);
insert into orders (id, product, quantity) values (3, 'Fond - Neutral', 6);
insert into orders (id, product, quantity) values (4, 'Salmon - Atlantic, Fresh, Whole', 2);
insert into orders (id, product, quantity) values (5, 'Bok Choy - Baby', 1);
insert into orders (id, product, quantity) values (6, 'Hot Choc Vending', 4);
insert into orders (id, product, quantity) values (7, 'Beef - Outside, Round', 7);
insert into orders (id, product, quantity) values (8, 'Cleaner - Pine Sol', 8);
insert into orders (id, product, quantity) values (9, 'Wine - Hardys Bankside Shiraz', 9);
insert into orders (id, product, quantity) values (10, 'Sugar - Cubes', 10);
insert into orders (id, product, quantity) values (11, 'Praline Paste', 3);
insert into orders (id, product, quantity) values (12, 'Beer - Tetleys', 8);
insert into orders (id, product, quantity) values (13, 'Mints - Striped Red', 7);
insert into orders (id, product, quantity) values (14, 'Sour Puss Sour Apple', 3);
insert into orders (id, product, quantity) values (15, 'Mcgillicuddy Vanilla Schnap', 9);
insert into orders (id, product, quantity) values (16, 'Tuna - Canned, Flaked, Light', 10);
insert into orders (id, product, quantity) values (17, 'Shrimp, Dried, Small / Lb', 3);
insert into orders (id, product, quantity) values (18, 'French Kiss Vanilla', 6);
insert into orders (id, product, quantity) values (19, 'Sauce - White, Mix', 2);
insert into orders (id, product, quantity) values (20, 'Galliano', 6);
insert into orders (id, product, quantity) values (21, 'Appetizer - Mini Egg Roll, Shrimp', 1);
insert into orders (id, product, quantity) values (22, 'Ostrich - Prime Cut', 2);
insert into orders (id, product, quantity) values (23, 'Flower - Potmums', 2);
insert into orders (id, product, quantity) values (24, 'Sambuca - Opal Nera', 1);
insert into orders (id, product, quantity) values (25, 'Soupfoamcont12oz 112con', 7);
insert into orders (id, product, quantity) values (26, 'Whmis Spray Bottle Graduated', 1);
insert into orders (id, product, quantity) values (27, 'V8 - Vegetable Cocktail', 5);
insert into orders (id, product, quantity) values (28, 'Sping Loaded Cup Dispenser', 2);
insert into orders (id, product, quantity) values (29, 'Pail - 15l White, With Handle', 10);
insert into orders (id, product, quantity) values (30, 'Chef Hat 20cm', 8);
insert into orders (id, product, quantity) values (31, 'Mop Head - Cotton, 24 Oz', 9);
insert into orders (id, product, quantity) values (32, 'Tia Maria', 6);
insert into orders (id, product, quantity) values (33, 'Veal - Bones', 9);
insert into orders (id, product, quantity) values (34, 'Wine - Shiraz South Eastern', 8);
insert into orders (id, product, quantity) values (35, 'Flour - Bread', 10);
insert into orders (id, product, quantity) values (36, 'Cornstarch', 2);
insert into orders (id, product, quantity) values (37, 'Extract - Lemon', 9);
insert into orders (id, product, quantity) values (38, 'Mushroom - Chanterelle, Dry', 2);
insert into orders (id, product, quantity) values (39, 'Sugar - Brown', 7);
insert into orders (id, product, quantity) values (40, 'Beer - Sleeman Fine Porter', 7);
insert into orders (id, product, quantity) values (41, 'Veal - Sweetbread', 8);
insert into orders (id, product, quantity) values (42, 'Coffee Swiss Choc Almond', 2);
insert into orders (id, product, quantity) values (43, 'Ice Cream - Turtles Stick Bar', 3);
insert into orders (id, product, quantity) values (44, 'Table Cloth 91x91 Colour', 10);
insert into orders (id, product, quantity) values (45, 'Flavouring - Orange', 5);
insert into orders (id, product, quantity) values (46, 'Hot Choc Vending', 3);
insert into orders (id, product, quantity) values (47, 'Cookie Dough - Chocolate Chip', 6);
insert into orders (id, product, quantity) values (48, 'Club Soda - Schweppes, 355 Ml', 3);
insert into orders (id, product, quantity) values (49, 'Wine - Cabernet Sauvignon', 4);
insert into orders (id, product, quantity) values (50, 'Salsify, Organic', 3);
insert into orders (id, product, quantity) values (51, 'Napkin - Cocktail,beige 2 - Ply', 4);
insert into orders (id, product, quantity) values (52, 'Chicken - Wieners', 5);
insert into orders (id, product, quantity) values (53, 'Cookie Dough - Chocolate Chip', 7);
insert into orders (id, product, quantity) values (54, 'Veal - Tenderloin, Untrimmed', 5);
insert into orders (id, product, quantity) values (55, 'Shark - Loin', 5);
insert into orders (id, product, quantity) values (56, 'Bread - Roll, Italian', 10);
insert into orders (id, product, quantity) values (57, 'Cheese - Gouda Smoked', 1);
insert into orders (id, product, quantity) values (58, 'Wine - Two Oceans Sauvignon', 7);
insert into orders (id, product, quantity) values (59, 'Fond - Neutral', 6);
insert into orders (id, product, quantity) values (60, 'Cornflakes', 8);
insert into orders (id, product, quantity) values (61, 'Oyster - In Shell', 3);
insert into orders (id, product, quantity) values (62, 'Duck - Fat', 9);
insert into orders (id, product, quantity) values (63, 'Veal - Leg', 4);
insert into orders (id, product, quantity) values (64, 'Lid Tray - 12in Dome', 5);
insert into orders (id, product, quantity) values (65, 'Cookies - Englishbay Chochip', 1);
insert into orders (id, product, quantity) values (66, 'Muffin Mix - Lemon Cranberry', 8);
insert into orders (id, product, quantity) values (67, 'Trout - Smoked', 1);
insert into orders (id, product, quantity) values (68, 'Mahi Mahi', 8);
insert into orders (id, product, quantity) values (69, 'Mince Meat - Filling', 1);
insert into orders (id, product, quantity) values (70, 'Cheese - Gorgonzola', 7);
insert into orders (id, product, quantity) values (71, 'Allspice - Jamaican', 8);
insert into orders (id, product, quantity) values (72, 'Cheese - Havarti, Roasted Garlic', 1);
insert into orders (id, product, quantity) values (73, 'Sachet', 1);
insert into orders (id, product, quantity) values (74, 'Syrup - Golden, Lyles', 3);
insert into orders (id, product, quantity) values (75, 'Pork - Hock And Feet Attached', 2);
insert into orders (id, product, quantity) values (76, 'Onions Granulated', 2);
insert into orders (id, product, quantity) values (77, 'Soup - Campbells Pasta Fagioli', 10);
insert into orders (id, product, quantity) values (78, 'Lemonade - Island Tea, 591 Ml', 8);
insert into orders (id, product, quantity) values (79, 'Pineapple - Canned, Rings', 3);
insert into orders (id, product, quantity) values (80, 'Sauce - Salsa', 3);
insert into orders (id, product, quantity) values (81, 'Hand Towel', 4);
insert into orders (id, product, quantity) values (82, 'Chicken Thigh - Bone Out', 6);
insert into orders (id, product, quantity) values (83, 'Cocktail Napkin Blue', 3);
insert into orders (id, product, quantity) values (84, 'Soup - Knorr, Classic Can. Chili', 3);
insert into orders (id, product, quantity) values (85, 'Soup - Campbells, Minestrone', 5);
insert into orders (id, product, quantity) values (86, 'Lettuce - Green Leaf', 4);
insert into orders (id, product, quantity) values (87, 'Bacardi Limon', 2);
insert into orders (id, product, quantity) values (88, 'Ham - Procutinni', 1);
insert into orders (id, product, quantity) values (89, 'Pasta - Canelloni, Single Serve', 5);
insert into orders (id, product, quantity) values (90, 'Wine - Ice Wine', 7);
insert into orders (id, product, quantity) values (91, 'Beef - Baby, Liver', 3);
insert into orders (id, product, quantity) values (92, 'Tomato - Tricolor Cherry', 6);
insert into orders (id, product, quantity) values (93, 'Lemonade - Black Cherry, 591 Ml', 8);
insert into orders (id, product, quantity) values (94, 'Soup - Base Broth Beef', 2);
insert into orders (id, product, quantity) values (95, 'Mussels - Frozen', 10);
insert into orders (id, product, quantity) values (96, 'Eggplant - Baby', 10);
insert into orders (id, product, quantity) values (97, 'Artichokes - Knobless, White', 7);
insert into orders (id, product, quantity) values (98, 'Papadam', 8);
insert into orders (id, product, quantity) values (99, 'Island Oasis - Cappucino Mix', 10);
insert into orders (id, product, quantity) values (100, 'Bagel - 12 Grain Preslice', 10);
insert into orders (id, product, quantity) values (101, 'Pop - Club Soda Can', 7);
insert into orders (id, product, quantity) values (102, 'Flower - Potmums', 6);
insert into orders (id, product, quantity) values (103, 'Cheese - Brie', 3);
insert into orders (id, product, quantity) values (104, 'Extract - Raspberry', 2);
insert into orders (id, product, quantity) values (105, 'Radish', 4);
insert into orders (id, product, quantity) values (106, 'Macaroons - Two Bite Choc', 10);
insert into orders (id, product, quantity) values (107, 'Shrimp, Dried, Small / Lb', 9);
insert into orders (id, product, quantity) values (108, 'Chicken - Soup Base', 3);
insert into orders (id, product, quantity) values (109, 'Higashimaru Usukuchi Soy', 1);
insert into orders (id, product, quantity) values (110, 'Wine - Shiraz South Eastern', 1);
insert into orders (id, product, quantity) values (111, 'Dip - Tapenade', 8);
insert into orders (id, product, quantity) values (112, 'Compound - Passion Fruit', 4);
insert into orders (id, product, quantity) values (113, 'Pickle - Dill', 4);
insert into orders (id, product, quantity) values (114, 'Trueblue - Blueberry Cranberry', 4);
insert into orders (id, product, quantity) values (115, 'Bread - Roll, Calabrese', 6);
insert into orders (id, product, quantity) values (116, 'Bagel - Ched Chs Presliced', 10);
insert into orders (id, product, quantity) values (117, 'Chips - Assorted', 10);
insert into orders (id, product, quantity) values (118, 'Carbonated Water - Blackcherry', 7);
insert into orders (id, product, quantity) values (119, 'Fish - Base, Bouillion', 10);
insert into orders (id, product, quantity) values (120, 'Kiwano', 1);
insert into orders (id, product, quantity) values (121, 'Chinese Foods - Pepper Beef', 2);
insert into orders (id, product, quantity) values (122, 'Wine - Zonnebloem Pinotage', 9);
insert into orders (id, product, quantity) values (123, 'Bacardi Limon', 7);
insert into orders (id, product, quantity) values (124, 'Sauce - Apple, Unsweetened', 4);
insert into orders (id, product, quantity) values (125, 'Wine - Champagne Brut Veuve', 7);
insert into orders (id, product, quantity) values (126, 'Sunflower Seed Raw', 5);
insert into orders (id, product, quantity) values (127, 'Chocolate - Dark', 9);
insert into orders (id, product, quantity) values (128, 'Veal - Bones', 7);
insert into orders (id, product, quantity) values (129, 'Blouse / Shirt / Sweater', 5);
insert into orders (id, product, quantity) values (130, 'Iced Tea - Lemon, 460 Ml', 5);
insert into orders (id, product, quantity) values (131, 'Juice - Prune', 9);
insert into orders (id, product, quantity) values (132, 'Dikon', 5);
insert into orders (id, product, quantity) values (133, 'Chocolate Liqueur - Godet White', 2);
insert into orders (id, product, quantity) values (134, 'Silicone Parch. 16.3x24.3', 1);
insert into orders (id, product, quantity) values (135, 'Beef - Prime Rib Aaa', 5);
insert into orders (id, product, quantity) values (136, 'Flour - Strong Pizza', 9);
insert into orders (id, product, quantity) values (137, 'Icecream - Dstk Super Cone', 8);
insert into orders (id, product, quantity) values (138, 'Laundry - Bag Cloth', 1);
insert into orders (id, product, quantity) values (139, 'Rice - 7 Grain Blend', 1);
insert into orders (id, product, quantity) values (140, 'Broom - Corn', 2);
insert into orders (id, product, quantity) values (141, 'Carbonated Water - Blackcherry', 5);
insert into orders (id, product, quantity) values (142, 'Pork - Loin, Center Cut', 1);
insert into orders (id, product, quantity) values (143, 'Soy Protein', 9);
insert into orders (id, product, quantity) values (144, 'Beans - Black Bean, Preserved', 4);
insert into orders (id, product, quantity) values (145, 'Wine - Red, Pinot Noir, Chateau', 7);
insert into orders (id, product, quantity) values (146, 'Egg Patty Fried', 2);
insert into orders (id, product, quantity) values (147, 'Breakfast Quesadillas', 3);
insert into orders (id, product, quantity) values (148, 'Onions - Spanish', 6);
insert into orders (id, product, quantity) values (149, 'Swiss Chard', 8);
insert into orders (id, product, quantity) values (150, 'Garlic', 3);
insert into orders (id, product, quantity) values (151, 'Ecolab Crystal Fusion', 9);
insert into orders (id, product, quantity) values (152, 'Lettuce - Arugula', 8);
insert into orders (id, product, quantity) values (153, 'Bouillion - Fish', 1);
insert into orders (id, product, quantity) values (154, 'Potatoes - Instant, Mashed', 4);
insert into orders (id, product, quantity) values (155, 'Relish', 10);
insert into orders (id, product, quantity) values (156, 'Dip - Tapenade', 5);
insert into orders (id, product, quantity) values (157, 'Pepper - Scotch Bonnet', 7);
insert into orders (id, product, quantity) values (158, 'Ginger - Pickled', 5);
insert into orders (id, product, quantity) values (159, 'Cheese - Cheddar, Mild', 2);
insert into orders (id, product, quantity) values (160, 'Seedlings - Buckwheat, Organic', 3);
insert into orders (id, product, quantity) values (161, 'Coke - Classic, 355 Ml', 1);
insert into orders (id, product, quantity) values (162, 'Cheese - Mozzarella, Shredded', 6);
insert into orders (id, product, quantity) values (163, 'Olives - Morracan Dired', 10);
insert into orders (id, product, quantity) values (164, 'Bread - Kimel Stick Poly', 10);
insert into orders (id, product, quantity) values (165, 'Banana - Green', 8);
insert into orders (id, product, quantity) values (166, 'Veal - Insides, Grains', 7);
insert into orders (id, product, quantity) values (167, 'Beef - Tenderloin Tails', 3);
insert into orders (id, product, quantity) values (168, 'Wine - Sauvignon Blanc Oyster', 6);
insert into orders (id, product, quantity) values (169, 'Flower - Dish Garden', 2);
insert into orders (id, product, quantity) values (170, 'Juice - Pineapple, 341 Ml', 1);
insert into orders (id, product, quantity) values (171, 'Tuna - Canned, Flaked, Light', 5);
insert into orders (id, product, quantity) values (172, 'Port - 74 Brights', 1);
insert into orders (id, product, quantity) values (173, 'Coffee - Irish Cream', 2);
insert into orders (id, product, quantity) values (174, 'Bread Base - Gold Formel', 2);
insert into orders (id, product, quantity) values (175, 'Steamers White', 5);
insert into orders (id, product, quantity) values (176, 'Apples - Spartan', 6);
insert into orders (id, product, quantity) values (177, 'Lobster - Tail 6 Oz', 2);
insert into orders (id, product, quantity) values (178, 'Lemonade - Kiwi, 591 Ml', 9);
insert into orders (id, product, quantity) values (179, 'Nut - Almond, Blanched, Ground', 1);
insert into orders (id, product, quantity) values (180, 'Cheese - Brie', 1);
insert into orders (id, product, quantity) values (181, 'Aspic - Clear', 1);
insert into orders (id, product, quantity) values (182, 'Sansho Powder', 10);
insert into orders (id, product, quantity) values (183, 'Dish Towel', 10);
insert into orders (id, product, quantity) values (184, 'Muffin Mix - Lemon Cranberry', 6);
insert into orders (id, product, quantity) values (185, 'Nestea - Ice Tea, Diet', 1);
insert into orders (id, product, quantity) values (186, 'Tuna - Salad Premix', 9);
insert into orders (id, product, quantity) values (187, 'Pails With Lids', 4);
insert into orders (id, product, quantity) values (188, 'Wine - White Cab Sauv.on', 5);
insert into orders (id, product, quantity) values (189, 'Pears - Anjou', 2);
insert into orders (id, product, quantity) values (190, 'Rabbit - Saddles', 8);
insert into orders (id, product, quantity) values (191, 'Cheese - Brie, Cups 125g', 2);
insert into orders (id, product, quantity) values (192, 'Glass Clear 8 Oz', 7);
insert into orders (id, product, quantity) values (193, 'Appetizer - Escargot Puff', 10);
insert into orders (id, product, quantity) values (194, 'Beef - Tongue, Cooked', 6);
insert into orders (id, product, quantity) values (195, 'Fireball Whisky', 1);
insert into orders (id, product, quantity) values (196, 'Pants Custom Dry Clean', 7);
insert into orders (id, product, quantity) values (197, 'Mushroom - Morels, Dry', 8);
insert into orders (id, product, quantity) values (198, 'Salmon Steak - Cohoe 6 Oz', 5);
insert into orders (id, product, quantity) values (199, 'Wine - White, Antinore Orvieto', 1);
insert into orders (id, product, quantity) values (200, 'Cheese - Gorgonzola', 4);
insert into orders (id, product, quantity) values (201, 'Basil - Thai', 1);
insert into orders (id, product, quantity) values (202, 'Oil - Olive Bertolli', 10);
insert into orders (id, product, quantity) values (203, 'Cookie - Dough Variety', 6);
insert into orders (id, product, quantity) values (204, 'Veal - Provimi Inside', 3);
insert into orders (id, product, quantity) values (205, 'Butter - Pod', 3);
insert into orders (id, product, quantity) values (206, 'Rice Wine - Aji Mirin', 3);
insert into orders (id, product, quantity) values (207, 'Wine - White, Pinot Grigio', 2);
insert into orders (id, product, quantity) values (208, 'Salt And Pepper Mix - Black', 6);
insert into orders (id, product, quantity) values (209, 'English Muffin', 8);
insert into orders (id, product, quantity) values (210, 'Mushrooms - Honey', 10);
insert into orders (id, product, quantity) values (211, 'Iced Tea Concentrate', 2);
insert into orders (id, product, quantity) values (212, 'Wine - Red, Colio Cabernet', 8);
insert into orders (id, product, quantity) values (213, 'Wine - Sherry Dry Sack, William', 4);
insert into orders (id, product, quantity) values (214, 'Pasta - Fusili, Dry', 5);
insert into orders (id, product, quantity) values (215, 'Sachet', 7);
insert into orders (id, product, quantity) values (216, 'Cheese - La Sauvagine', 9);
insert into orders (id, product, quantity) values (217, 'Mustard - Pommery', 1);
insert into orders (id, product, quantity) values (218, 'Curry Powder', 7);
insert into orders (id, product, quantity) values (219, 'Pears - Bartlett', 10);
insert into orders (id, product, quantity) values (220, 'The Pop Shoppe - Cream Soda', 2);
insert into orders (id, product, quantity) values (221, 'Carrots - Jumbo', 9);
insert into orders (id, product, quantity) values (222, 'Strawberries', 4);
insert into orders (id, product, quantity) values (223, 'Sambuca - Ramazzotti', 5);
insert into orders (id, product, quantity) values (224, 'Bread - Sour Sticks With Onion', 6);
insert into orders (id, product, quantity) values (225, 'Corn - On The Cob', 4);
insert into orders (id, product, quantity) values (226, 'Vodka - Lemon, Absolut', 9);
insert into orders (id, product, quantity) values (227, 'Chick Peas - Canned', 4);
insert into orders (id, product, quantity) values (228, 'Tumeric', 6);
insert into orders (id, product, quantity) values (229, 'Bread Base - Gold Formel', 7);
insert into orders (id, product, quantity) values (230, 'Onion - Dried', 2);
insert into orders (id, product, quantity) values (231, 'Chips - Assorted', 8);
insert into orders (id, product, quantity) values (232, 'Carrots - Mini Red Organic', 4);
insert into orders (id, product, quantity) values (233, 'Arizona - Plum Green Tea', 3);
insert into orders (id, product, quantity) values (234, 'Wine - Black Tower Qr', 9);
insert into orders (id, product, quantity) values (235, 'Soup - Verve - Chipotle Chicken', 4);
insert into orders (id, product, quantity) values (236, 'Cheese - Parmigiano Reggiano', 8);
insert into orders (id, product, quantity) values (237, 'Chicken - Diced, Cooked', 1);
insert into orders (id, product, quantity) values (238, 'Lemonade - Pineapple Passion', 10);
insert into orders (id, product, quantity) values (239, 'Kahlua', 7);
insert into orders (id, product, quantity) values (240, 'Tea - Herbal - 6 Asst', 9);
insert into orders (id, product, quantity) values (241, 'Vermacelli - Sprinkles, Assorted', 1);
insert into orders (id, product, quantity) values (242, 'Cream - 18%', 1);
insert into orders (id, product, quantity) values (243, 'Cheese - Gouda', 3);
insert into orders (id, product, quantity) values (244, 'Bread - Roll, Calabrese', 10);
insert into orders (id, product, quantity) values (245, 'Cheese - Feta', 3);
insert into orders (id, product, quantity) values (246, 'Coffee Caramel Biscotti', 10);
insert into orders (id, product, quantity) values (247, 'Rosemary - Dry', 9);
insert into orders (id, product, quantity) values (248, 'Kaffir Lime Leaves', 8);
insert into orders (id, product, quantity) values (249, 'Stock - Veal, Brown', 8);
insert into orders (id, product, quantity) values (250, 'Bread - Calabrese Baguette', 7);
insert into orders (id, product, quantity) values (251, 'Kippers - Smoked', 2);
insert into orders (id, product, quantity) values (252, 'Mustard - Dry, Powder', 10);
insert into orders (id, product, quantity) values (253, 'Lettuce - Iceberg', 5);
insert into orders (id, product, quantity) values (254, 'Island Oasis - Strawberry', 1);
insert into orders (id, product, quantity) values (255, 'Chips Potato Reg 43g', 3);
insert into orders (id, product, quantity) values (256, 'Rum - Mount Gay Eclipes', 4);
insert into orders (id, product, quantity) values (257, 'Wine - Magnotta - Cab Franc', 10);
insert into orders (id, product, quantity) values (258, 'Tomato Puree', 10);
insert into orders (id, product, quantity) values (259, 'Nantucket Apple Juice', 5);
insert into orders (id, product, quantity) values (260, 'Pork - Ham Hocks - Smoked', 1);
insert into orders (id, product, quantity) values (261, 'Chocolate Bar - Oh Henry', 1);
insert into orders (id, product, quantity) values (262, 'Wine - Duboeuf Beaujolais', 7);
insert into orders (id, product, quantity) values (263, 'Dikon', 3);
insert into orders (id, product, quantity) values (264, 'Thyme - Fresh', 7);
insert into orders (id, product, quantity) values (265, 'Chocolate - Pistoles, Lactee, Milk', 7);
insert into orders (id, product, quantity) values (266, 'Tuna - Sushi Grade', 8);
insert into orders (id, product, quantity) values (267, 'Vinegar - Sherry', 6);
insert into orders (id, product, quantity) values (268, 'Cheese - Victor Et Berthold', 3);
insert into orders (id, product, quantity) values (269, 'Limes', 7);
insert into orders (id, product, quantity) values (270, 'Syrup - Kahlua Chocolate', 3);
insert into orders (id, product, quantity) values (271, 'Campari', 3);
insert into orders (id, product, quantity) values (272, 'Cup - 8oz Coffee Perforated', 5);
insert into orders (id, product, quantity) values (273, 'Wine - Acient Coast Caberne', 2);
insert into orders (id, product, quantity) values (274, 'Chives - Fresh', 8);
insert into orders (id, product, quantity) values (275, 'Appetizer - Smoked Salmon / Dill', 10);
insert into orders (id, product, quantity) values (276, 'Mangostein', 8);
insert into orders (id, product, quantity) values (277, 'Sesame Seed Black', 3);
insert into orders (id, product, quantity) values (278, 'Rice - Jasmine Sented', 4);
insert into orders (id, product, quantity) values (279, 'Peas Snow', 2);
insert into orders (id, product, quantity) values (280, 'Tart Shells - Sweet, 2', 1);
insert into orders (id, product, quantity) values (281, 'Noodles - Steamed Chow Mein', 9);
insert into orders (id, product, quantity) values (282, 'Bread - Wheat Baguette', 4);
insert into orders (id, product, quantity) values (283, 'Rhubarb', 5);
insert into orders (id, product, quantity) values (284, 'Sparkling Wine - Rose, Freixenet', 1);
insert into orders (id, product, quantity) values (285, 'Shrimp - Prawn', 10);
insert into orders (id, product, quantity) values (286, 'Energy Drink - Franks Original', 1);
insert into orders (id, product, quantity) values (287, 'Lobster - Cooked', 8);
insert into orders (id, product, quantity) values (288, 'Sugar - Palm', 6);
insert into orders (id, product, quantity) values (289, 'Puree - Pear', 7);
insert into orders (id, product, quantity) values (290, 'Mushroom - Portebello', 3);
insert into orders (id, product, quantity) values (291, 'Wine - Red, Marechal Foch', 9);
insert into orders (id, product, quantity) values (292, 'Truffle Cups - White Paper', 10);
insert into orders (id, product, quantity) values (293, 'Rosemary - Primerba, Paste', 10);
insert into orders (id, product, quantity) values (294, 'Calypso - Black Cherry Lemonade', 4);
insert into orders (id, product, quantity) values (295, 'Chinese Lemon Pork', 1);
insert into orders (id, product, quantity) values (296, 'Sugar - Splenda Sweetener', 2);
insert into orders (id, product, quantity) values (297, 'Dill Weed - Fresh', 4);
insert into orders (id, product, quantity) values (298, 'Vinegar - Champagne', 3);
insert into orders (id, product, quantity) values (299, 'Chilli Paste, Hot Sambal Oelek', 5);
insert into orders (id, product, quantity) values (300, 'Cheese - Stilton', 3);
insert into orders (id, product, quantity) values (301, 'Anisette - Mcguiness', 9);
insert into orders (id, product, quantity) values (302, 'Veal - Leg, Provimi - 50 Lb Max', 3);
insert into orders (id, product, quantity) values (303, 'V8 Pet', 7);
insert into orders (id, product, quantity) values (304, 'Pepper - Chilli Seeds Mild', 10);
insert into orders (id, product, quantity) values (305, 'Langers - Ruby Red Grapfruit', 10);
insert into orders (id, product, quantity) values (306, 'Bread - French Stick', 7);
insert into orders (id, product, quantity) values (307, 'Bread - Pita, Mini', 5);
insert into orders (id, product, quantity) values (308, 'Roe - Flying Fish', 6);
insert into orders (id, product, quantity) values (309, 'Coffee Cup 12oz 5342cd', 10);
insert into orders (id, product, quantity) values (310, 'Wine - Periguita Fonseca', 1);
insert into orders (id, product, quantity) values (311, 'Salt - Table', 2);
insert into orders (id, product, quantity) values (312, 'Teriyaki Sauce', 4);
insert into orders (id, product, quantity) values (313, 'Wine - White, Schroder And Schyl', 9);
insert into orders (id, product, quantity) values (314, 'Sage Ground Wiberg', 3);
insert into orders (id, product, quantity) values (315, 'Sugar - White Packet', 3);
insert into orders (id, product, quantity) values (316, 'Cookie Dough - Double', 6);
insert into orders (id, product, quantity) values (317, 'Swiss Chard', 7);
insert into orders (id, product, quantity) values (318, 'Fish - Artic Char, Cold Smoked', 6);
insert into orders (id, product, quantity) values (319, 'Strawberries', 10);
insert into orders (id, product, quantity) values (320, 'Otomegusa Dashi Konbu', 7);
insert into orders (id, product, quantity) values (321, 'Bar Bran Honey Nut', 4);
insert into orders (id, product, quantity) values (322, 'Beans - Navy, Dry', 3);
insert into orders (id, product, quantity) values (323, 'Bread - Wheat Baguette', 7);
insert into orders (id, product, quantity) values (324, 'Flour - Chickpea', 6);
insert into orders (id, product, quantity) values (325, 'Longos - Penne With Pesto', 1);
insert into orders (id, product, quantity) values (326, 'Seabream Whole Farmed', 3);
insert into orders (id, product, quantity) values (327, 'Campari', 10);
insert into orders (id, product, quantity) values (328, 'Melon - Watermelon, Seedless', 4);
insert into orders (id, product, quantity) values (329, 'Lettuce - Treviso', 9);
insert into orders (id, product, quantity) values (330, 'Cleaner - Pine Sol', 1);
insert into orders (id, product, quantity) values (331, 'Chicken Giblets', 8);
insert into orders (id, product, quantity) values (332, 'Sprouts - China Rose', 8);
insert into orders (id, product, quantity) values (333, 'Sugar - Brown', 9);
insert into orders (id, product, quantity) values (334, 'Coriander - Ground', 2);
insert into orders (id, product, quantity) values (335, 'Tart Shells - Sweet, 2', 9);
insert into orders (id, product, quantity) values (336, 'Wine - White, Concha Y Toro', 5);
insert into orders (id, product, quantity) values (337, 'Capon - Breast, Wing On', 7);
insert into orders (id, product, quantity) values (338, 'Cheese - Comte', 10);
insert into orders (id, product, quantity) values (339, 'Oil - Avocado', 8);
insert into orders (id, product, quantity) values (340, 'Pears - Fiorelle', 7);
insert into orders (id, product, quantity) values (341, 'Pastry - Apple Large', 9);
insert into orders (id, product, quantity) values (342, 'Vinegar - Cider', 7);
insert into orders (id, product, quantity) values (343, 'Beef - Roasted, Cooked', 5);
insert into orders (id, product, quantity) values (344, 'Rum - Mount Gay Eclipes', 9);
insert into orders (id, product, quantity) values (345, 'Cranberries - Fresh', 5);
insert into orders (id, product, quantity) values (346, 'Bols Melon Liqueur', 3);
insert into orders (id, product, quantity) values (347, 'Cup Translucent 9 Oz', 9);
insert into orders (id, product, quantity) values (348, 'Pear - Prickly', 5);
insert into orders (id, product, quantity) values (349, 'Bread - Multigrain, Loaf', 4);
insert into orders (id, product, quantity) values (350, 'Basil - Dry, Rubbed', 4);
insert into orders (id, product, quantity) values (351, 'Cranberries - Dry', 8);
insert into orders (id, product, quantity) values (352, 'Mousse - Passion Fruit', 8);
insert into orders (id, product, quantity) values (353, 'Whmis - Spray Bottle Trigger', 2);
insert into orders (id, product, quantity) values (354, 'Cabbage - Nappa', 6);
insert into orders (id, product, quantity) values (355, 'Lamb Tenderloin Nz Fr', 4);
insert into orders (id, product, quantity) values (356, 'Mustard Prepared', 8);
insert into orders (id, product, quantity) values (357, 'Sauce - Gravy, Au Jus, Mix', 3);
insert into orders (id, product, quantity) values (358, 'Quiche Assorted', 6);
insert into orders (id, product, quantity) values (359, 'Water - Aquafina Vitamin', 4);
insert into orders (id, product, quantity) values (360, 'Nut - Almond, Blanched, Ground', 3);
insert into orders (id, product, quantity) values (361, 'Transfer Sheets', 9);
insert into orders (id, product, quantity) values (362, 'Teriyaki Sauce', 1);
insert into orders (id, product, quantity) values (363, 'Soup - Campbells Broccoli', 8);
insert into orders (id, product, quantity) values (364, 'Crush - Grape, 355 Ml', 6);
insert into orders (id, product, quantity) values (365, 'Cookies - Amaretto', 2);
insert into orders (id, product, quantity) values (366, 'Lettuce - Boston Bib', 9);
insert into orders (id, product, quantity) values (367, 'Dill - Primerba, Paste', 7);
insert into orders (id, product, quantity) values (368, 'Soup - Campbells, Creamy', 1);
insert into orders (id, product, quantity) values (369, 'Versatainer Nc - 9388', 6);
insert into orders (id, product, quantity) values (370, 'Chocolate - Milk Coating', 2);
insert into orders (id, product, quantity) values (371, 'Juice - Apple, 341 Ml', 3);
insert into orders (id, product, quantity) values (372, 'Beef - Rib Eye Aaa', 5);
insert into orders (id, product, quantity) values (373, 'Soup Knorr Chili With Beans', 5);
insert into orders (id, product, quantity) values (374, 'Pork Loin Cutlets', 7);
insert into orders (id, product, quantity) values (375, 'Longos - Chicken Cordon Bleu', 4);
insert into orders (id, product, quantity) values (376, 'Flour - Teff', 10);
insert into orders (id, product, quantity) values (377, 'Soy Protein', 9);
insert into orders (id, product, quantity) values (378, 'Bag - Bread, White, Plain', 7);
insert into orders (id, product, quantity) values (379, 'Ginger - Ground', 10);
insert into orders (id, product, quantity) values (380, 'Sauce - Salsa', 8);
insert into orders (id, product, quantity) values (381, 'Cheese - Havarti, Salsa', 4);
insert into orders (id, product, quantity) values (382, 'Bread Ww Cluster', 7);
insert into orders (id, product, quantity) values (383, 'Wine - Gewurztraminer Pierre', 2);
insert into orders (id, product, quantity) values (384, 'Wine - Red, Cooking', 8);
insert into orders (id, product, quantity) values (385, 'Cheese - Cambozola', 5);
insert into orders (id, product, quantity) values (386, 'Nut - Almond, Blanched, Whole', 4);
insert into orders (id, product, quantity) values (387, 'Tray - 16in Rnd Blk', 7);
insert into orders (id, product, quantity) values (388, 'Flour - Chickpea', 7);
insert into orders (id, product, quantity) values (389, 'Coffee - French Vanilla Frothy', 8);
insert into orders (id, product, quantity) values (390, 'Squash - Sunburst', 2);
insert into orders (id, product, quantity) values (391, 'Soup - French Onion, Dry', 10);
insert into orders (id, product, quantity) values (392, 'Arizona - Green Tea', 4);
insert into orders (id, product, quantity) values (393, 'Wine - Barolo Fontanafredda', 3);
insert into orders (id, product, quantity) values (394, 'Bag - Bread, White, Plain', 6);
insert into orders (id, product, quantity) values (395, 'Chip - Potato Dill Pickle', 3);
insert into orders (id, product, quantity) values (396, 'Irish Cream - Butterscotch', 3);
insert into orders (id, product, quantity) values (397, 'Rice - Sushi', 10);
insert into orders (id, product, quantity) values (398, 'Anisette - Mcguiness', 8);
insert into orders (id, product, quantity) values (399, 'Grapes - Red', 1);
insert into orders (id, product, quantity) values (400, 'Blackberries', 10);
insert into orders (id, product, quantity) values (401, 'Beef - Bones, Cut - Up', 8);
insert into orders (id, product, quantity) values (402, 'Rabbit - Whole', 9);
insert into orders (id, product, quantity) values (403, 'Soup Campbells Split Pea And Ham', 7);
insert into orders (id, product, quantity) values (404, 'Cream Of Tartar', 4);
insert into orders (id, product, quantity) values (405, 'Bulgar', 1);
insert into orders (id, product, quantity) values (406, 'Pepper - White, Ground', 5);
insert into orders (id, product, quantity) values (407, 'Filter - Coffee', 8);
insert into orders (id, product, quantity) values (408, 'Ice Cream - Vanilla', 2);
insert into orders (id, product, quantity) values (409, 'Glass Clear 7 Oz Xl', 8);
insert into orders (id, product, quantity) values (410, 'Bread - Rolls, Rye', 2);
insert into orders (id, product, quantity) values (411, 'Vinegar - Rice', 4);
insert into orders (id, product, quantity) values (412, 'Pork - Bacon,back Peameal', 6);
insert into orders (id, product, quantity) values (413, 'Wine - Sogrape Mateus Rose', 2);
insert into orders (id, product, quantity) values (414, 'Coffee - Flavoured', 10);
insert into orders (id, product, quantity) values (415, 'Beef - Flank Steak', 9);
insert into orders (id, product, quantity) values (416, 'Turkey - Breast, Double', 4);
insert into orders (id, product, quantity) values (417, 'Yogurt - Raspberry, 175 Gr', 4);
insert into orders (id, product, quantity) values (418, 'Wood Chips - Regular', 2);
insert into orders (id, product, quantity) values (419, 'Glass Clear 8 Oz', 8);
insert into orders (id, product, quantity) values (420, 'Lettuce - Curly Endive', 5);
insert into orders (id, product, quantity) values (421, 'Flax Seed', 7);
insert into orders (id, product, quantity) values (422, 'Bread - Italian Sesame Poly', 1);
insert into orders (id, product, quantity) values (423, 'Juice - V8 Splash', 9);
insert into orders (id, product, quantity) values (424, 'Soup - Campbells, Cream Of', 1);
insert into orders (id, product, quantity) values (425, 'Poppy Seed', 9);
insert into orders (id, product, quantity) values (426, 'Bar Special K', 5);
insert into orders (id, product, quantity) values (427, 'Melon - Watermelon, Seedless', 6);
insert into orders (id, product, quantity) values (428, 'Veal - Kidney', 2);
insert into orders (id, product, quantity) values (429, 'Cheese - Fontina', 8);
insert into orders (id, product, quantity) values (430, 'V8 Splash Strawberry Kiwi', 4);
insert into orders (id, product, quantity) values (431, 'Beans - Black Bean, Canned', 10);
insert into orders (id, product, quantity) values (432, 'Pectin', 5);
insert into orders (id, product, quantity) values (433, 'Trueblue - Blueberry Cranberry', 1);
insert into orders (id, product, quantity) values (434, 'Butter - Pod', 9);
insert into orders (id, product, quantity) values (435, 'Sansho Powder', 8);
insert into orders (id, product, quantity) values (436, 'Ginger - Crystalized', 9);
insert into orders (id, product, quantity) values (437, 'Milk - 1%', 4);
insert into orders (id, product, quantity) values (438, 'Cloves - Ground', 1);
insert into orders (id, product, quantity) values (439, 'Seedlings - Mix, Organic', 2);
insert into orders (id, product, quantity) values (440, 'Muffin - Bran Ind Wrpd', 9);
insert into orders (id, product, quantity) values (441, 'V8 Splash Strawberry Kiwi', 6);
insert into orders (id, product, quantity) values (442, 'Anisette - Mcguiness', 4);
insert into orders (id, product, quantity) values (443, 'Bread - Assorted Rolls', 10);
insert into orders (id, product, quantity) values (444, 'Wine - Beaujolais Villages', 9);
insert into orders (id, product, quantity) values (445, 'Magnotta - Bel Paese White', 3);
insert into orders (id, product, quantity) values (446, 'Mix - Cocktail Strawberry Daiquiri', 9);
insert into orders (id, product, quantity) values (447, 'Pur Source', 7);
insert into orders (id, product, quantity) values (448, 'Water - Green Tea Refresher', 6);
insert into orders (id, product, quantity) values (449, 'Pumpkin', 10);
insert into orders (id, product, quantity) values (450, 'Wine - Sherry Dry Sack, William', 9);
insert into orders (id, product, quantity) values (451, 'Cheese Cheddar Processed', 6);
insert into orders (id, product, quantity) values (452, 'Oil - Sunflower', 8);
insert into orders (id, product, quantity) values (453, 'Bread - Olive', 6);
insert into orders (id, product, quantity) values (454, 'Oil - Avocado', 4);
insert into orders (id, product, quantity) values (455, 'Appetizer - Southwestern', 8);
insert into orders (id, product, quantity) values (456, 'Flour - Bread', 4);
insert into orders (id, product, quantity) values (457, 'Pasta - Canelloni, Single Serve', 7);
insert into orders (id, product, quantity) values (458, 'Grenadine', 7);
insert into orders (id, product, quantity) values (459, 'Aspic - Light', 8);
insert into orders (id, product, quantity) values (460, 'Cheese Cloth No 100', 3);
insert into orders (id, product, quantity) values (461, 'Pork - Liver', 5);
insert into orders (id, product, quantity) values (462, 'Spice - Peppercorn Melange', 10);
insert into orders (id, product, quantity) values (463, 'Bar Special K', 1);
insert into orders (id, product, quantity) values (464, 'Cookie Chocolate Chip With', 8);
insert into orders (id, product, quantity) values (465, 'Beef - Tenderloin', 6);
insert into orders (id, product, quantity) values (466, 'Beef - Ox Tongue, Pickled', 1);
insert into orders (id, product, quantity) values (467, 'Cherries - Fresh', 10);
insert into orders (id, product, quantity) values (468, 'Beef - Tongue, Fresh', 6);
insert into orders (id, product, quantity) values (469, 'Ham - Cooked Italian', 2);
insert into orders (id, product, quantity) values (470, 'Wine - Soave Folonari', 1);
insert into orders (id, product, quantity) values (471, 'Filo Dough', 7);
insert into orders (id, product, quantity) values (472, 'Soap - Pine Sol Floor Cleaner', 10);
insert into orders (id, product, quantity) values (473, 'Butter - Salted', 3);
insert into orders (id, product, quantity) values (474, 'Pastry - Cherry Danish - Mini', 10);
insert into orders (id, product, quantity) values (475, 'Beer - True North Lager', 5);
insert into orders (id, product, quantity) values (476, 'Creme De Menthe Green', 8);
insert into orders (id, product, quantity) values (477, 'Wine - Dubouef Macon - Villages', 1);
insert into orders (id, product, quantity) values (478, 'Kahlua', 5);
insert into orders (id, product, quantity) values (479, 'Sauce - Thousand Island', 8);
insert into orders (id, product, quantity) values (480, 'Compound - Orange', 5);
insert into orders (id, product, quantity) values (481, 'Veal - Osso Bucco', 4);
insert into orders (id, product, quantity) values (482, 'Coffee - Decaffeinato Coffee', 5);
insert into orders (id, product, quantity) values (483, 'Cinnamon Buns Sticky', 9);
insert into orders (id, product, quantity) values (484, 'Bacardi Breezer - Tropical', 7);
insert into orders (id, product, quantity) values (485, 'Brandy - Bar', 5);
insert into orders (id, product, quantity) values (486, 'Mustard - Individual Pkg', 5);
insert into orders (id, product, quantity) values (487, 'Pimento - Canned', 7);
insert into orders (id, product, quantity) values (488, 'Juice - Apple, 1.36l', 5);
insert into orders (id, product, quantity) values (489, 'Rum - Dark, Bacardi, Black', 10);
insert into orders (id, product, quantity) values (490, 'Lambcasing', 6);
insert into orders (id, product, quantity) values (491, 'Tuna - Yellowfin', 4);
insert into orders (id, product, quantity) values (492, 'Rice - 7 Grain Blend', 8);
insert into orders (id, product, quantity) values (493, 'Quail - Jumbo', 5);
insert into orders (id, product, quantity) values (494, 'Pants Custom Dry Clean', 9);
insert into orders (id, product, quantity) values (495, 'Chives - Fresh', 6);
insert into orders (id, product, quantity) values (496, 'Cup - Paper 10oz 92959', 8);
insert into orders (id, product, quantity) values (497, 'Sherbet - Raspberry', 2);
insert into orders (id, product, quantity) values (498, 'Beef - Kobe Striploin', 4);
insert into orders (id, product, quantity) values (499, 'Cheese - Parmesan Cubes', 7);
insert into orders (id, product, quantity) values (500, 'Cumin - Ground', 1);
insert into orders (id, product, quantity) values (501, 'Pike - Frozen Fillet', 7);
insert into orders (id, product, quantity) values (502, 'Island Oasis - Pina Colada', 6);
insert into orders (id, product, quantity) values (503, 'Bread Roll Foccacia', 2);
insert into orders (id, product, quantity) values (504, 'Amaretto', 2);
insert into orders (id, product, quantity) values (505, 'Cheese - Le Cheve Noir', 7);
insert into orders (id, product, quantity) values (506, 'Liners - Banana, Paper', 4);
insert into orders (id, product, quantity) values (507, 'Red Currants', 4);
insert into orders (id, product, quantity) values (508, 'Flour - Buckwheat, Dark', 7);
insert into orders (id, product, quantity) values (509, 'Vodka - Hot, Lnferno', 3);
insert into orders (id, product, quantity) values (510, 'Lamb - Sausage Casings', 4);
insert into orders (id, product, quantity) values (511, 'Mushroom - Shitake, Fresh', 6);
insert into orders (id, product, quantity) values (512, 'Soup - Campbellschix Stew', 8);
insert into orders (id, product, quantity) values (513, 'Coconut - Whole', 8);
insert into orders (id, product, quantity) values (514, 'Pumpkin', 2);
insert into orders (id, product, quantity) values (515, 'Chevril', 1);
insert into orders (id, product, quantity) values (516, 'Beef - Ground Medium', 5);
insert into orders (id, product, quantity) values (517, 'Bread - English Muffin', 2);
insert into orders (id, product, quantity) values (518, 'Vinegar - Rice', 4);
insert into orders (id, product, quantity) values (519, 'Syrup - Chocolate', 5);
insert into orders (id, product, quantity) values (520, 'Veal - Chops, Split, Frenched', 9);
insert into orders (id, product, quantity) values (521, 'Cod - Black Whole Fillet', 5);
insert into orders (id, product, quantity) values (522, 'Wine - Carmenere Casillero Del', 10);
insert into orders (id, product, quantity) values (523, 'Island Oasis - Raspberry', 5);
insert into orders (id, product, quantity) values (524, 'Ice Cream Bar - Hagen Daz', 6);
insert into orders (id, product, quantity) values (525, 'Beer - Alexander Kieths, Pale Ale', 8);
insert into orders (id, product, quantity) values (526, 'Syrup - Monin - Granny Smith', 1);
insert into orders (id, product, quantity) values (527, 'Milk - 1%', 8);
insert into orders (id, product, quantity) values (528, 'Pasta - Orzo, Dry', 8);
insert into orders (id, product, quantity) values (529, 'Leeks - Baby, White', 6);
insert into orders (id, product, quantity) values (530, 'Blackberries', 7);
insert into orders (id, product, quantity) values (531, 'Wine - Ej Gallo Sierra Valley', 3);
insert into orders (id, product, quantity) values (532, 'Rice - Jasmine Sented', 5);
insert into orders (id, product, quantity) values (533, 'Guinea Fowl', 2);
insert into orders (id, product, quantity) values (534, 'Squash - Sunburst', 9);
insert into orders (id, product, quantity) values (535, 'Sea Bass - Fillets', 7);
insert into orders (id, product, quantity) values (536, 'Carbonated Water - Peach', 5);
insert into orders (id, product, quantity) values (537, 'Wine - Marlbourough Sauv Blanc', 9);
insert into orders (id, product, quantity) values (538, 'Lettuce - Iceberg', 4);
insert into orders (id, product, quantity) values (539, 'Nori Sea Weed - Gold Label', 9);
insert into orders (id, product, quantity) values (540, 'Star Anise, Whole', 2);
insert into orders (id, product, quantity) values (541, 'Tea - Earl Grey', 9);
insert into orders (id, product, quantity) values (542, 'Milk - 2% 250 Ml', 2);
insert into orders (id, product, quantity) values (543, 'Spinach - Baby', 3);
insert into orders (id, product, quantity) values (544, 'Rice - Long Grain', 5);
insert into orders (id, product, quantity) values (545, 'Soup Campbells - Tomato Bisque', 4);
insert into orders (id, product, quantity) values (546, 'Vinegar - White Wine', 5);
insert into orders (id, product, quantity) values (547, 'Mahi Mahi', 9);
insert into orders (id, product, quantity) values (548, 'Pastrami', 2);
insert into orders (id, product, quantity) values (549, 'Ecolab - Ster Bac', 4);
insert into orders (id, product, quantity) values (550, 'Red Snapper - Fresh, Whole', 7);
insert into orders (id, product, quantity) values (551, 'Pastry - French Mini Assorted', 9);
insert into orders (id, product, quantity) values (552, 'Red Snapper - Fillet, Skin On', 10);
insert into orders (id, product, quantity) values (553, 'Tray - 16in Rnd Blk', 6);
insert into orders (id, product, quantity) values (554, 'Dikon', 5);
insert into orders (id, product, quantity) values (555, 'Corn Meal', 1);
insert into orders (id, product, quantity) values (556, 'Sardines', 5);
insert into orders (id, product, quantity) values (557, 'Pasta - Cappellini, Dry', 8);
insert into orders (id, product, quantity) values (558, 'Rice - Jasmine Sented', 7);
insert into orders (id, product, quantity) values (559, 'Pastrami', 9);
insert into orders (id, product, quantity) values (560, 'Beer - Moosehead', 8);
insert into orders (id, product, quantity) values (561, 'Cheese - La Sauvagine', 6);
insert into orders (id, product, quantity) values (562, 'Cookie Double Choco', 8);
insert into orders (id, product, quantity) values (563, 'Sugar - Brown, Individual', 1);
insert into orders (id, product, quantity) values (564, 'Bread - Roll, Italian', 10);
insert into orders (id, product, quantity) values (565, 'Temperature Recording Station', 7);
insert into orders (id, product, quantity) values (566, 'Pancetta', 2);
insert into orders (id, product, quantity) values (567, 'Veal - Knuckle', 5);
insert into orders (id, product, quantity) values (568, 'Chicken - Whole', 10);
insert into orders (id, product, quantity) values (569, 'Pumpkin - Seed', 6);
insert into orders (id, product, quantity) values (570, 'Wine - White, Lindemans Bin 95', 2);
insert into orders (id, product, quantity) values (571, 'Lemon Grass', 7);
insert into orders (id, product, quantity) values (572, 'Doilies - 10, Paper', 10);
insert into orders (id, product, quantity) values (573, 'Turkey - Oven Roast Breast', 9);
insert into orders (id, product, quantity) values (574, 'Chocolate - Dark Callets', 4);
insert into orders (id, product, quantity) values (575, 'Carroway Seed', 10);
insert into orders (id, product, quantity) values (576, 'Carbonated Water - Orange', 3);
insert into orders (id, product, quantity) values (577, 'Scrubbie - Scotchbrite Hand Pad', 1);
insert into orders (id, product, quantity) values (578, 'Nestea - Iced Tea', 4);
insert into orders (id, product, quantity) values (579, 'Neckerchief Blck', 8);
insert into orders (id, product, quantity) values (580, 'Ham - Cooked Bayonne Tinned', 4);
insert into orders (id, product, quantity) values (581, 'Kellogs All Bran Bars', 5);
insert into orders (id, product, quantity) values (582, 'Sausage - Chorizo', 9);
insert into orders (id, product, quantity) values (583, 'Icecream Bar - Del Monte', 4);
insert into orders (id, product, quantity) values (584, 'Sugar - Invert', 8);
insert into orders (id, product, quantity) values (585, 'Beef - Striploin', 10);
insert into orders (id, product, quantity) values (586, 'Peach - Halves', 8);
insert into orders (id, product, quantity) values (587, 'Banana Turning', 3);
insert into orders (id, product, quantity) values (588, 'Bacardi Limon', 4);
insert into orders (id, product, quantity) values (589, 'Orange - Tangerine', 9);
insert into orders (id, product, quantity) values (590, 'Schnappes - Peach, Walkers', 9);
insert into orders (id, product, quantity) values (591, 'Wine - Penfolds Koonuga Hill', 1);
insert into orders (id, product, quantity) values (592, 'Coffee Guatemala Dark', 10);
insert into orders (id, product, quantity) values (593, 'Cinnamon - Ground', 3);
insert into orders (id, product, quantity) values (594, 'Table Cloth 53x69 White', 4);
insert into orders (id, product, quantity) values (595, 'Soup Bowl Clear 8oz92008', 3);
insert into orders (id, product, quantity) values (596, 'Quail - Jumbo', 2);
insert into orders (id, product, quantity) values (597, 'Artichoke - Hearts, Canned', 2);
insert into orders (id, product, quantity) values (598, 'Shichimi Togarashi Peppeers', 1);
insert into orders (id, product, quantity) values (599, 'Wine - Prosecco Valdobienne', 6);
insert into orders (id, product, quantity) values (600, 'Ice Cream - Life Savers', 10);
insert into orders (id, product, quantity) values (601, 'Extract Vanilla Pure', 4);
insert into orders (id, product, quantity) values (602, 'Mousse - Mango', 4);
insert into orders (id, product, quantity) values (603, 'Ham - Procutinni', 3);
insert into orders (id, product, quantity) values (604, 'Kolrabi', 9);
insert into orders (id, product, quantity) values (605, 'Ecolab - Hobart Upr Prewash Arm', 3);
insert into orders (id, product, quantity) values (606, 'Crackers - Melba Toast', 5);
insert into orders (id, product, quantity) values (607, 'Pasta - Angel Hair', 3);
insert into orders (id, product, quantity) values (608, 'Squid U5 - Thailand', 5);
insert into orders (id, product, quantity) values (609, 'Bag - Clear 7 Lb', 4);
insert into orders (id, product, quantity) values (610, 'Pasta - Cappellini, Dry', 3);
insert into orders (id, product, quantity) values (611, 'Cheese - Gouda', 2);
insert into orders (id, product, quantity) values (612, 'Doilies - 10, Paper', 9);
insert into orders (id, product, quantity) values (613, 'Milk - Chocolate 250 Ml', 1);
insert into orders (id, product, quantity) values (614, 'Beef - Rib Roast, Capless', 10);
insert into orders (id, product, quantity) values (615, 'Sour Puss Sour Apple', 3);
insert into orders (id, product, quantity) values (616, 'Longos - Cheese Tortellini', 9);
insert into orders (id, product, quantity) values (617, 'Juice - Orangina', 4);
insert into orders (id, product, quantity) values (618, 'Pasta - Detalini, White, Fresh', 6);
insert into orders (id, product, quantity) values (619, 'Fiddlehead - Frozen', 8);
insert into orders (id, product, quantity) values (620, 'Pizza Pizza Dough', 7);
insert into orders (id, product, quantity) values (621, 'Bread - Bagels, Plain', 9);
insert into orders (id, product, quantity) values (622, 'Muffin - Blueberry Individual', 7);
insert into orders (id, product, quantity) values (623, 'Sole - Fillet', 5);
insert into orders (id, product, quantity) values (624, 'Cut Wakame - Hanawakaba', 1);
insert into orders (id, product, quantity) values (625, 'Pork - Tenderloin, Fresh', 8);
insert into orders (id, product, quantity) values (626, 'Steampan Lid', 2);
insert into orders (id, product, quantity) values (627, 'Mangostein', 8);
insert into orders (id, product, quantity) values (628, 'Cake - Cheese Cake 9 Inch', 6);
insert into orders (id, product, quantity) values (629, 'Mustard - Seed', 4);
insert into orders (id, product, quantity) values (630, 'Sausage - Liver', 8);
insert into orders (id, product, quantity) values (631, 'Nut - Hazelnut, Whole', 1);
insert into orders (id, product, quantity) values (632, 'Russian Prince', 7);
insert into orders (id, product, quantity) values (633, 'Soup - Campbells Chili Veg', 6);
insert into orders (id, product, quantity) values (634, 'Tea - Orange Pekoe', 4);
insert into orders (id, product, quantity) values (635, 'Doilies - 10, Paper', 7);
insert into orders (id, product, quantity) values (636, 'Pork - Tenderloin, Fresh', 3);
insert into orders (id, product, quantity) values (637, 'Sugar - Individual Portions', 8);
insert into orders (id, product, quantity) values (638, 'Shiro Miso', 3);
insert into orders (id, product, quantity) values (639, 'Wine - Rosso Del Veronese Igt', 9);
insert into orders (id, product, quantity) values (640, 'Silicone Paper 16.5x24', 5);
insert into orders (id, product, quantity) values (641, 'Sugar - Icing', 7);
insert into orders (id, product, quantity) values (642, 'Mince Meat - Filling', 10);
insert into orders (id, product, quantity) values (643, 'Butter Balls Salted', 5);
insert into orders (id, product, quantity) values (644, 'Table Cloth 120 Round White', 1);
insert into orders (id, product, quantity) values (645, 'Split Peas - Green, Dry', 6);
insert into orders (id, product, quantity) values (646, 'Honey - Comb', 6);
insert into orders (id, product, quantity) values (647, 'Fiddlehead - Frozen', 8);
insert into orders (id, product, quantity) values (648, 'Grapefruit - White', 4);
insert into orders (id, product, quantity) values (649, 'Veal - Brisket, Provimi, Bone - In', 10);
insert into orders (id, product, quantity) values (650, 'Coffee Caramel Biscotti', 5);
insert into orders (id, product, quantity) values (651, 'Stock - Chicken, White', 3);
insert into orders (id, product, quantity) values (652, 'Pasta - Fettuccine, Egg, Fresh', 3);
insert into orders (id, product, quantity) values (653, 'Fish - Artic Char, Cold Smoked', 2);
insert into orders (id, product, quantity) values (654, 'Snapple Lemon Tea', 2);
insert into orders (id, product, quantity) values (655, 'Lobak', 10);
insert into orders (id, product, quantity) values (656, 'Jolt Cola', 2);
insert into orders (id, product, quantity) values (657, 'Sauce - Soy Low Sodium - 3.87l', 3);
insert into orders (id, product, quantity) values (658, 'Wine - Fino Tio Pepe Gonzalez', 6);
insert into orders (id, product, quantity) values (659, 'Glass Clear 7 Oz Xl', 9);
insert into orders (id, product, quantity) values (660, 'Cheese - Wine', 5);
insert into orders (id, product, quantity) values (661, 'Longos - Penne With Pesto', 8);
insert into orders (id, product, quantity) values (662, 'Cafe Royale', 4);
insert into orders (id, product, quantity) values (663, 'Latex Rubber Gloves Size 9', 2);
insert into orders (id, product, quantity) values (664, 'Soup - Campbells, Lentil', 7);
insert into orders (id, product, quantity) values (665, 'Sage - Fresh', 3);
insert into orders (id, product, quantity) values (666, 'Muffin Mix - Blueberry', 9);
insert into orders (id, product, quantity) values (667, 'Spinach - Baby', 3);
insert into orders (id, product, quantity) values (668, 'Chocolate - White', 4);
insert into orders (id, product, quantity) values (669, 'Muskox - French Rack', 5);
insert into orders (id, product, quantity) values (670, 'Arrowroot', 2);
insert into orders (id, product, quantity) values (671, 'Shrimp - 16 - 20 Cooked, Peeled', 7);
insert into orders (id, product, quantity) values (672, 'Smoked Tongue', 2);
insert into orders (id, product, quantity) values (673, 'Beef - Roasted, Cooked', 9);
insert into orders (id, product, quantity) values (674, 'Venison - Denver Leg Boneless', 6);
insert into orders (id, product, quantity) values (675, 'Spinach - Baby', 7);
insert into orders (id, product, quantity) values (676, 'Pears - Anjou', 4);
insert into orders (id, product, quantity) values (677, 'Veal - Heart', 8);
insert into orders (id, product, quantity) values (678, 'Beef Tenderloin Aaa', 8);
insert into orders (id, product, quantity) values (679, 'Island Oasis - Lemonade', 9);
insert into orders (id, product, quantity) values (680, 'Muffin - Blueberry Individual', 6);
insert into orders (id, product, quantity) values (681, 'Sobe - Berry Energy', 10);
insert into orders (id, product, quantity) values (682, 'Miso Paste White', 8);
insert into orders (id, product, quantity) values (683, 'Truffle Cups - Red', 7);
insert into orders (id, product, quantity) values (684, 'Jicama', 10);
insert into orders (id, product, quantity) values (685, 'Remy Red', 5);
insert into orders (id, product, quantity) values (686, 'Kellogs Raisan Bran Bars', 4);
insert into orders (id, product, quantity) values (687, 'Shrimp - 21/25, Peel And Deviened', 6);
insert into orders (id, product, quantity) values (688, 'Orange Roughy 6/8 Oz', 9);
insert into orders (id, product, quantity) values (689, 'Lettuce - Green Leaf', 10);
insert into orders (id, product, quantity) values (690, 'Juice - Apple Cider', 2);
insert into orders (id, product, quantity) values (691, 'Ecolab - Ster Bac', 7);
insert into orders (id, product, quantity) values (692, 'Straw - Regular', 10);
insert into orders (id, product, quantity) values (693, 'Bacardi Mojito', 10);
insert into orders (id, product, quantity) values (694, 'Sorrel - Fresh', 4);
insert into orders (id, product, quantity) values (695, 'Tuna - Sushi Grade', 7);
insert into orders (id, product, quantity) values (696, 'Pepper - Chipotle, Canned', 3);
insert into orders (id, product, quantity) values (697, 'Bacardi Limon', 1);
insert into orders (id, product, quantity) values (698, 'Energy Drink - Franks Pineapple', 6);
insert into orders (id, product, quantity) values (699, 'Rice - Basmati', 1);
insert into orders (id, product, quantity) values (700, 'Melon - Watermelon, Seedless', 7);
insert into orders (id, product, quantity) values (701, 'Pork - Kidney', 10);
insert into orders (id, product, quantity) values (702, 'Veal - Heart', 9);
insert into orders (id, product, quantity) values (703, 'Tomatoes Tear Drop', 5);
insert into orders (id, product, quantity) values (704, 'Buttons', 3);
insert into orders (id, product, quantity) values (705, 'Shark - Loin', 10);
insert into orders (id, product, quantity) values (706, 'Seedlings - Buckwheat, Organic', 7);
insert into orders (id, product, quantity) values (707, 'Squid - Breaded', 5);
insert into orders (id, product, quantity) values (708, 'Flour - Chickpea', 8);
insert into orders (id, product, quantity) values (709, 'Catfish - Fillets', 4);
insert into orders (id, product, quantity) values (710, 'Wine - White, Pelee Island', 10);
insert into orders (id, product, quantity) values (711, 'Turkey Leg With Drum And Thigh', 6);
insert into orders (id, product, quantity) values (712, 'Cup - Translucent 7 Oz Clear', 7);
insert into orders (id, product, quantity) values (713, 'Seedlings - Clamshell', 6);
insert into orders (id, product, quantity) values (714, 'Pork - Sausage Casing', 10);
insert into orders (id, product, quantity) values (715, 'Fondant - Icing', 4);
insert into orders (id, product, quantity) values (716, 'Pork - Backs - Boneless', 7);
insert into orders (id, product, quantity) values (717, 'Cumin - Ground', 1);
insert into orders (id, product, quantity) values (718, 'Lamb Tenderloin Nz Fr', 4);
insert into orders (id, product, quantity) values (719, 'Water - Aquafina Vitamin', 10);
insert into orders (id, product, quantity) values (720, 'Chevril', 1);
insert into orders (id, product, quantity) values (721, 'Soup Campbells', 2);
insert into orders (id, product, quantity) values (722, 'Pepper - Orange', 3);
insert into orders (id, product, quantity) values (723, 'Beef - Montreal Smoked Brisket', 5);
insert into orders (id, product, quantity) values (724, 'Arctic Char - Fillets', 9);
insert into orders (id, product, quantity) values (725, 'Burger Veggie', 7);
insert into orders (id, product, quantity) values (726, 'Compound - Passion Fruit', 8);
insert into orders (id, product, quantity) values (727, 'Pop Shoppe Cream Soda', 7);
insert into orders (id, product, quantity) values (728, 'Iced Tea - Lemon, 340ml', 6);
insert into orders (id, product, quantity) values (729, 'Broom And Brush Rack Black', 10);
insert into orders (id, product, quantity) values (730, 'Cup - Translucent 7 Oz Clear', 7);
insert into orders (id, product, quantity) values (731, 'Soupcontfoam16oz 116con', 1);
insert into orders (id, product, quantity) values (732, 'Glass - Wine, Plastic, Clear 5 Oz', 3);
insert into orders (id, product, quantity) values (733, 'Bols Melon Liqueur', 5);
insert into orders (id, product, quantity) values (734, 'Oil - Cooking Spray', 7);
insert into orders (id, product, quantity) values (735, 'Juice - Cranberry 284ml', 9);
insert into orders (id, product, quantity) values (736, 'Onions - Red', 5);
insert into orders (id, product, quantity) values (737, 'Coffee - Espresso', 7);
insert into orders (id, product, quantity) values (738, 'Garbage Bags - Black', 5);
insert into orders (id, product, quantity) values (739, 'Pasta - Rotini, Colour, Dry', 3);
insert into orders (id, product, quantity) values (740, 'Pike - Frozen Fillet', 3);
insert into orders (id, product, quantity) values (741, 'Coffee - Colombian, Portioned', 1);
insert into orders (id, product, quantity) values (742, 'Beer - Corona', 10);
insert into orders (id, product, quantity) values (743, 'Pear - Packum', 8);
insert into orders (id, product, quantity) values (744, 'Cheese - La Sauvagine', 8);
insert into orders (id, product, quantity) values (745, 'Mackerel Whole Fresh', 1);
insert into orders (id, product, quantity) values (746, 'Halibut - Whole, Fresh', 9);
insert into orders (id, product, quantity) values (747, 'Sauce - Marinara', 9);
insert into orders (id, product, quantity) values (748, 'Beer - Pilsner Urquell', 2);
insert into orders (id, product, quantity) values (749, 'Artichoke - Hearts, Canned', 1);
insert into orders (id, product, quantity) values (750, 'Chocolate - Feathers', 10);
insert into orders (id, product, quantity) values (751, 'Nantuket Peach Orange', 5);
insert into orders (id, product, quantity) values (752, 'Basil - Fresh', 5);
insert into orders (id, product, quantity) values (753, 'Kiwi', 2);
insert into orders (id, product, quantity) values (754, 'Pesto - Primerba, Paste', 1);
insert into orders (id, product, quantity) values (755, 'Bread - Frozen Basket Variety', 8);
insert into orders (id, product, quantity) values (756, 'Tofu - Firm', 9);
insert into orders (id, product, quantity) values (757, 'Pepper - Red Thai', 2);
insert into orders (id, product, quantity) values (758, 'Mushroom - Morels, Dry', 7);
insert into orders (id, product, quantity) values (759, 'Beer - Mill St Organic', 3);
insert into orders (id, product, quantity) values (760, 'Lamb - Whole, Fresh', 2);
insert into orders (id, product, quantity) values (761, 'Onion - Dried', 3);
insert into orders (id, product, quantity) values (762, 'Bagel - Whole White Sesame', 7);
insert into orders (id, product, quantity) values (763, 'Flower - Dish Garden', 10);
insert into orders (id, product, quantity) values (764, 'Bread - Corn Muffaleta Onion', 1);
insert into orders (id, product, quantity) values (765, 'Wine - Carmenere Casillero Del', 5);
insert into orders (id, product, quantity) values (766, 'Lighter - Bbq', 7);
insert into orders (id, product, quantity) values (767, 'Mustard - Individual Pkg', 8);
insert into orders (id, product, quantity) values (768, 'Tuna - Salad Premix', 3);
insert into orders (id, product, quantity) values (769, 'Chicken - White Meat, No Tender', 10);
insert into orders (id, product, quantity) values (770, 'Beer - Alexander Kieths, Pale Ale', 7);
insert into orders (id, product, quantity) values (771, 'Catfish - Fillets', 6);
insert into orders (id, product, quantity) values (772, 'Coffee - 10oz Cup 92961', 1);
insert into orders (id, product, quantity) values (773, 'Higashimaru Usukuchi Soy', 2);
insert into orders (id, product, quantity) values (774, 'Fish - Artic Char, Cold Smoked', 9);
insert into orders (id, product, quantity) values (775, 'Beer - Mcauslan Apricot', 7);
insert into orders (id, product, quantity) values (776, 'Wine - Penfolds Koonuga Hill', 3);
insert into orders (id, product, quantity) values (777, 'Chilli Paste, Ginger Garlic', 1);
insert into orders (id, product, quantity) values (778, 'Chinese Foods - Cantonese', 10);
insert into orders (id, product, quantity) values (779, 'Island Oasis - Ice Cream Mix', 10);
insert into orders (id, product, quantity) values (780, 'Cherries - Maraschino,jar', 5);
insert into orders (id, product, quantity) values (781, 'Tuna - Yellowfin', 3);
insert into orders (id, product, quantity) values (782, 'Kippers - Smoked', 6);
insert into orders (id, product, quantity) values (783, 'Chips - Assorted', 1);
insert into orders (id, product, quantity) values (784, 'Long Island Ice Tea', 9);
insert into orders (id, product, quantity) values (785, 'Chicken - Leg / Back Attach', 3);
insert into orders (id, product, quantity) values (786, 'Bread Ww Cluster', 1);
insert into orders (id, product, quantity) values (787, 'Longos - Assorted Sandwich', 6);
insert into orders (id, product, quantity) values (788, 'Venison - Denver Leg Boneless', 9);
insert into orders (id, product, quantity) values (789, 'Wine - White Cab Sauv.on', 6);
insert into orders (id, product, quantity) values (790, 'Vector Energy Bar', 4);
insert into orders (id, product, quantity) values (791, 'Pectin', 6);
insert into orders (id, product, quantity) values (792, 'Chicken - Leg, Fresh', 9);
insert into orders (id, product, quantity) values (793, 'Juice - Ocean Spray Kiwi', 10);
insert into orders (id, product, quantity) values (794, 'Dragon Fruit', 3);
insert into orders (id, product, quantity) values (795, 'Pork - Ham, Virginia', 8);
insert into orders (id, product, quantity) values (796, 'Nantucket - Kiwi Berry Cktl.', 9);
insert into orders (id, product, quantity) values (797, 'Cookie - Oatmeal', 8);
insert into orders (id, product, quantity) values (798, 'Tomatoes - Diced, Canned', 6);
insert into orders (id, product, quantity) values (799, 'Beer - Muskoka Cream Ale', 2);
insert into orders (id, product, quantity) values (800, 'Napkin - Beverge, White 2 - Ply', 8);
insert into orders (id, product, quantity) values (801, 'Barramundi', 3);
insert into orders (id, product, quantity) values (802, 'Lettuce - Romaine', 4);
insert into orders (id, product, quantity) values (803, 'Table Cloth 81x81 Colour', 1);
insert into orders (id, product, quantity) values (804, 'Cheese - Victor Et Berthold', 1);
insert into orders (id, product, quantity) values (805, 'Pasta - Bauletti, Chicken White', 6);
insert into orders (id, product, quantity) values (806, 'Champagne - Brights, Dry', 9);
insert into orders (id, product, quantity) values (807, 'Brownies - Two Bite, Chocolate', 3);
insert into orders (id, product, quantity) values (808, 'Langers - Cranberry Cocktail', 6);
insert into orders (id, product, quantity) values (809, 'Wine - Redchard Merritt', 7);
insert into orders (id, product, quantity) values (810, 'Crackers Cheez It', 10);
insert into orders (id, product, quantity) values (811, 'Squid - U 5', 5);
insert into orders (id, product, quantity) values (812, 'Muskox - French Rack', 9);
insert into orders (id, product, quantity) values (813, 'Soup - Campbells, Creamy', 2);
insert into orders (id, product, quantity) values (814, 'Shrimp - 16/20, Iqf, Shell On', 1);
insert into orders (id, product, quantity) values (815, 'Dry Ice', 10);
insert into orders (id, product, quantity) values (816, 'Pur Source', 5);
insert into orders (id, product, quantity) values (817, 'Wine - Crozes Hermitage E.', 3);
insert into orders (id, product, quantity) values (818, 'Oyster - In Shell', 9);
insert into orders (id, product, quantity) values (819, 'Cream - 10%', 9);
insert into orders (id, product, quantity) values (820, 'Squid Ink', 5);
insert into orders (id, product, quantity) values (821, 'Gooseberry', 10);
insert into orders (id, product, quantity) values (822, 'Brandy Apricot', 9);
insert into orders (id, product, quantity) values (823, 'Oysters - Smoked', 1);
insert into orders (id, product, quantity) values (824, 'Pepper - Sorrano', 8);
insert into orders (id, product, quantity) values (825, 'Icecream - Dibs', 8);
insert into orders (id, product, quantity) values (826, 'Compound - Passion Fruit', 3);
insert into orders (id, product, quantity) values (827, 'Cheese Cloth No 60', 10);
insert into orders (id, product, quantity) values (828, 'Rum - Cream, Amarula', 6);
insert into orders (id, product, quantity) values (829, 'Marsala - Sperone, Fine, D.o.c.', 6);
insert into orders (id, product, quantity) values (830, 'Coffee Beans - Chocolate', 4);
insert into orders (id, product, quantity) values (831, 'Vinegar - Champagne', 7);
insert into orders (id, product, quantity) values (832, 'Veal - Insides Provini', 1);
insert into orders (id, product, quantity) values (833, 'Beets - Pickled', 5);
insert into orders (id, product, quantity) values (834, 'Mayonnaise - Individual Pkg', 6);
insert into orders (id, product, quantity) values (835, 'Soup - Campbells Beef Stew', 6);
insert into orders (id, product, quantity) values (836, 'Kahlua', 5);
insert into orders (id, product, quantity) values (837, 'Milk 2% 500 Ml', 1);
insert into orders (id, product, quantity) values (838, 'Mangoes', 3);
insert into orders (id, product, quantity) values (839, 'Dried Cherries', 8);
insert into orders (id, product, quantity) values (840, 'Oregano - Dry, Rubbed', 4);
insert into orders (id, product, quantity) values (841, 'Chocolate Eclairs', 2);
insert into orders (id, product, quantity) values (842, 'Lettuce - Green Leaf', 3);
insert into orders (id, product, quantity) values (843, 'Lettuce - Sea / Sea Asparagus', 5);
insert into orders (id, product, quantity) values (844, 'Rabbit - Frozen', 4);
insert into orders (id, product, quantity) values (845, 'Wine - Magnotta, Merlot Sr Vqa', 9);
insert into orders (id, product, quantity) values (846, 'Beets - Pickled', 4);
insert into orders (id, product, quantity) values (847, 'Snapple Lemon Tea', 3);
insert into orders (id, product, quantity) values (848, 'Cleaner - Lime Away', 2);
insert into orders (id, product, quantity) values (849, 'Table Cloth 54x54 White', 2);
insert into orders (id, product, quantity) values (850, 'Tomato - Plum With Basil', 10);
insert into orders (id, product, quantity) values (851, 'Wine - Fat Bastard Merlot', 7);
insert into orders (id, product, quantity) values (852, 'Capers - Ox Eye Daisy', 8);
insert into orders (id, product, quantity) values (853, 'Ham - Virginia', 6);
insert into orders (id, product, quantity) values (854, 'Soup Campbells Turkey Veg.', 1);
insert into orders (id, product, quantity) values (855, 'Pernod', 1);
insert into orders (id, product, quantity) values (856, 'Plate Pie Foil', 6);
insert into orders (id, product, quantity) values (857, 'Juice - Ocean Spray Cranberry', 2);
insert into orders (id, product, quantity) values (858, 'Chocolate - White', 7);
insert into orders (id, product, quantity) values (859, 'Cheese - Oka', 10);
insert into orders (id, product, quantity) values (860, 'Sobe - Tropical Energy', 9);
insert into orders (id, product, quantity) values (861, 'Bread Crumbs - Panko', 1);
insert into orders (id, product, quantity) values (862, 'Longos - Lasagna Veg', 7);
insert into orders (id, product, quantity) values (863, 'Bread - Pita, Mini', 7);
insert into orders (id, product, quantity) values (864, 'Eggplant - Asian', 2);
insert into orders (id, product, quantity) values (865, 'Wine - Shiraz South Eastern', 3);
insert into orders (id, product, quantity) values (866, 'Cake - Mini Potato Pancake', 5);
insert into orders (id, product, quantity) values (867, 'Bread - Italian Sesame Poly', 9);
insert into orders (id, product, quantity) values (868, 'Fond - Neutral', 9);
insert into orders (id, product, quantity) values (869, 'Foil - Round Foil', 7);
insert into orders (id, product, quantity) values (870, 'Lemon Grass', 5);
insert into orders (id, product, quantity) values (871, 'Plate Pie Foil', 5);
insert into orders (id, product, quantity) values (872, 'Wine - Pinot Noir Latour', 7);
insert into orders (id, product, quantity) values (873, 'Pepper Squash', 9);
insert into orders (id, product, quantity) values (874, 'Longos - Lasagna Beef', 1);
insert into orders (id, product, quantity) values (875, 'Cheese - Bakers Cream Cheese', 10);
insert into orders (id, product, quantity) values (876, 'Gatorade - Lemon Lime', 1);
insert into orders (id, product, quantity) values (877, 'Wine - Merlot Vina Carmen', 9);
insert into orders (id, product, quantity) values (878, 'Cornish Hen', 8);
insert into orders (id, product, quantity) values (879, 'Flour - Cake', 10);
insert into orders (id, product, quantity) values (880, 'Peas - Pigeon, Dry', 6);
insert into orders (id, product, quantity) values (881, 'French Kiss Vanilla', 7);
insert into orders (id, product, quantity) values (882, 'Cheese - Mozzarella', 10);
insert into orders (id, product, quantity) values (883, 'Coffee - Hazelnut Cream', 4);
insert into orders (id, product, quantity) values (884, 'Pork - Ham Hocks - Smoked', 7);
insert into orders (id, product, quantity) values (885, 'Oil - Grapeseed Oil', 10);
insert into orders (id, product, quantity) values (886, 'Beans - Fine', 9);
insert into orders (id, product, quantity) values (887, 'Bread - 10 Grain Parisian', 10);
insert into orders (id, product, quantity) values (888, 'Lidsoupcont Rp12dn', 7);
insert into orders (id, product, quantity) values (889, 'Tomatillo', 1);
insert into orders (id, product, quantity) values (890, 'Bread - Olive Dinner Roll', 7);
insert into orders (id, product, quantity) values (891, 'Lid Tray - 12in Dome', 2);
insert into orders (id, product, quantity) values (892, 'Yeast Dry - Fermipan', 8);
insert into orders (id, product, quantity) values (893, 'Coffee - Flavoured', 5);
insert into orders (id, product, quantity) values (894, 'Soup - Chicken And Wild Rice', 3);
insert into orders (id, product, quantity) values (895, 'Sauce - Sesame Thai Dressing', 4);
insert into orders (id, product, quantity) values (896, 'Pop - Club Soda Can', 5);
insert into orders (id, product, quantity) values (897, 'Radish - Black, Winter, Organic', 9);
insert into orders (id, product, quantity) values (898, 'Uniform Linen Charge', 8);
insert into orders (id, product, quantity) values (899, 'Thyme - Fresh', 7);
insert into orders (id, product, quantity) values (900, 'Beer - True North Strong Ale', 1);
insert into orders (id, product, quantity) values (901, 'Eel - Smoked', 7);
insert into orders (id, product, quantity) values (902, 'Ecolab - Hobart Upr Prewash Arm', 8);
insert into orders (id, product, quantity) values (903, 'Island Oasis - Pina Colada', 3);
insert into orders (id, product, quantity) values (904, 'Sugar - Individual Portions', 10);
insert into orders (id, product, quantity) values (905, 'Bagelers - Cinn / Brown', 5);
insert into orders (id, product, quantity) values (906, 'Muffin Mix - Blueberry', 9);
insert into orders (id, product, quantity) values (907, 'Appetizer - Mushroom Tart', 1);
insert into orders (id, product, quantity) values (908, 'Soup - Base Broth Chix', 6);
insert into orders (id, product, quantity) values (909, 'Oil - Coconut', 8);
insert into orders (id, product, quantity) values (910, 'Sauce - Marinara', 8);
insert into orders (id, product, quantity) values (911, 'Soup - Knorr, Ministrone', 4);
insert into orders (id, product, quantity) values (912, 'Wine - Trimbach Pinot Blanc', 5);
insert into orders (id, product, quantity) values (913, 'Lid Coffeecup 12oz D9542b', 2);
insert into orders (id, product, quantity) values (914, 'Compound - Strawberry', 3);
insert into orders (id, product, quantity) values (915, 'Teriyaki Sauce', 1);
insert into orders (id, product, quantity) values (916, 'Lidsoupcont Rp12dn', 3);
insert into orders (id, product, quantity) values (917, 'Cookie - Oatmeal', 6);
insert into orders (id, product, quantity) values (918, 'Chicken - Tenderloin', 9);
insert into orders (id, product, quantity) values (919, 'Scallop - St. Jaques', 7);
insert into orders (id, product, quantity) values (920, 'Mix - Cocktail Ice Cream', 3);
insert into orders (id, product, quantity) values (921, 'Honey - Lavender', 8);
insert into orders (id, product, quantity) values (922, 'Beef - Kobe Striploin', 2);
insert into orders (id, product, quantity) values (923, 'Wine - Champagne Brut Veuve', 9);
insert into orders (id, product, quantity) values (924, 'Crush - Orange, 355ml', 3);
insert into orders (id, product, quantity) values (925, 'Wine - Chateau Aqueria Tavel', 10);
insert into orders (id, product, quantity) values (926, 'Rootbeer', 5);
insert into orders (id, product, quantity) values (927, 'Kiwi Gold Zespri', 9);
insert into orders (id, product, quantity) values (928, 'Cabbage - Savoy', 6);
insert into orders (id, product, quantity) values (929, 'Burger Veggie', 1);
insert into orders (id, product, quantity) values (930, 'Eggplant - Regular', 6);
insert into orders (id, product, quantity) values (931, 'Wine - Trimbach Pinot Blanc', 1);
insert into orders (id, product, quantity) values (932, 'Appetizer - Crab And Brie', 9);
insert into orders (id, product, quantity) values (933, 'Pasta - Cappellini, Dry', 1);
insert into orders (id, product, quantity) values (934, 'Bread - White, Unsliced', 5);
insert into orders (id, product, quantity) values (935, 'Cake - Cake Sheet Macaroon', 10);
insert into orders (id, product, quantity) values (936, 'Wheat - Soft Kernal Of Wheat', 5);
insert into orders (id, product, quantity) values (937, 'Muffin Mix - Corn Harvest', 2);
insert into orders (id, product, quantity) values (938, 'Sobe - Lizard Fuel', 5);
insert into orders (id, product, quantity) values (939, 'Olives - Green, Pitted', 10);
insert into orders (id, product, quantity) values (940, 'Sauce - Black Current, Dry Mix', 4);
insert into orders (id, product, quantity) values (941, 'Oil - Avocado', 7);
insert into orders (id, product, quantity) values (942, 'Jameson Irish Whiskey', 2);
insert into orders (id, product, quantity) values (943, 'Nescafe - Frothy French Vanilla', 3);
insert into orders (id, product, quantity) values (944, 'Mustard - Dry, Powder', 7);
insert into orders (id, product, quantity) values (945, 'Chevril', 6);
insert into orders (id, product, quantity) values (946, 'Maple Syrup', 5);
insert into orders (id, product, quantity) values (947, 'Lettuce - Romaine, Heart', 4);
insert into orders (id, product, quantity) values (948, 'Quail - Jumbo', 3);
insert into orders (id, product, quantity) values (949, 'Savory', 8);
insert into orders (id, product, quantity) values (950, 'Chilli Paste, Sambal Oelek', 6);
insert into orders (id, product, quantity) values (951, 'Sweet Pea Sprouts', 3);
insert into orders (id, product, quantity) values (952, 'Wine - Alsace Riesling Reserve', 7);
insert into orders (id, product, quantity) values (953, 'Muffin - Mix - Bran And Maple 15l', 4);
insert into orders (id, product, quantity) values (954, 'Asparagus - Green, Fresh', 4);
insert into orders (id, product, quantity) values (955, 'Wine - White, Colubia Cresh', 5);
insert into orders (id, product, quantity) values (956, 'Bread - 10 Grain Parisian', 10);
insert into orders (id, product, quantity) values (957, 'Pork - Smoked Back Bacon', 1);
insert into orders (id, product, quantity) values (958, 'Transfer Sheets', 4);
insert into orders (id, product, quantity) values (959, 'Cups 10oz Trans', 2);
insert into orders (id, product, quantity) values (960, 'Campari', 6);
insert into orders (id, product, quantity) values (961, 'Bread - Flat Bread', 1);
insert into orders (id, product, quantity) values (962, 'Chicken - Livers', 9);
insert into orders (id, product, quantity) values (963, 'Brandy Apricot', 2);
insert into orders (id, product, quantity) values (964, 'Gherkin - Sour', 9);
insert into orders (id, product, quantity) values (965, 'Pasta - Orzo, Dry', 3);
insert into orders (id, product, quantity) values (966, 'Beef - Tongue, Fresh', 5);
insert into orders (id, product, quantity) values (967, 'Beef - Roasted, Cooked', 7);
insert into orders (id, product, quantity) values (968, 'Cheese - Goat', 4);
insert into orders (id, product, quantity) values (969, 'Syrup - Pancake', 10);
insert into orders (id, product, quantity) values (970, 'Shrimp - 150 - 250', 4);
insert into orders (id, product, quantity) values (971, 'Placemat - Scallop, White', 8);
insert into orders (id, product, quantity) values (972, 'V8 Splash Strawberry Banana', 4);
insert into orders (id, product, quantity) values (973, 'Cranberries - Dry', 7);
insert into orders (id, product, quantity) values (974, 'Nut - Almond, Blanched, Sliced', 3);
insert into orders (id, product, quantity) values (975, 'Country Roll', 3);
insert into orders (id, product, quantity) values (976, 'Mince Meat - Filling', 1);
insert into orders (id, product, quantity) values (977, 'Pate - Cognac', 4);
insert into orders (id, product, quantity) values (978, 'Bread - White Epi Baguette', 10);
insert into orders (id, product, quantity) values (979, 'Tomatoes - Orange', 8);
insert into orders (id, product, quantity) values (980, 'Glass - Wine, Plastic, Clear 5 Oz', 2);
insert into orders (id, product, quantity) values (981, 'Scallops 60/80 Iqf', 4);
insert into orders (id, product, quantity) values (982, 'Carbonated Water - Lemon Lime', 8);
insert into orders (id, product, quantity) values (983, 'Silicone Parch. 16.3x24.3', 2);
insert into orders (id, product, quantity) values (984, 'Ecolab - Lime - A - Way 4/4 L', 7);
insert into orders (id, product, quantity) values (985, 'Pastry - Banana Muffin - Mini', 4);
insert into orders (id, product, quantity) values (986, 'Bread - Wheat Baguette', 6);
insert into orders (id, product, quantity) values (987, 'Wine - White, Riesling, Semi - Dry', 10);
insert into orders (id, product, quantity) values (988, 'Pepsi - 600ml', 6);
insert into orders (id, product, quantity) values (989, 'Gin - Gilbeys London, Dry', 3);
insert into orders (id, product, quantity) values (990, 'Sauce - White, Mix', 3);
insert into orders (id, product, quantity) values (991, 'Wiberg Super Cure', 4);
insert into orders (id, product, quantity) values (992, 'Liqueur Banana, Ramazzotti', 5);
insert into orders (id, product, quantity) values (993, 'Compound - Orange', 9);
insert into orders (id, product, quantity) values (994, 'Brandy Cherry - Mcguinness', 7);
insert into orders (id, product, quantity) values (995, 'Bag - Clear 7 Lb', 7);
insert into orders (id, product, quantity) values (996, 'Sponge Cake Mix - Chocolate', 7);
insert into orders (id, product, quantity) values (997, 'Ecolab - Ster Bac', 8);
insert into orders (id, product, quantity) values (998, 'Spice - Paprika', 4);
insert into orders (id, product, quantity) values (999, 'Cup - Paper 10oz 92959', 2);
insert into orders (id, product, quantity) values (1000, 'Truffle Cups Green', 1);
